[build]
builder = "dockerfile"
dockerfilePath = "src/backend/Dockerfile"

[deploy]
startCommand = "bundle exec rails server -p $PORT -b 0.0.0.0"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
